### Get a paginated list of roles.
# Description:
# - Retrieves a page of roles with optional filtering and sorting.
# - Requires ROLE_ADMIN, ROLE_TESTER, or ROLE_MODERATOR.

GET http://localhost:8444/api/v1/table/roles?page=0&size=20&sortBy=roleId&sortOrder=asc&roleNameFilter=
X-Requesting-App: nebula_rest_api
Authorization: Bearer YOUR_ACCESS_TOKEN_HERE
Accept: application/hal+json
